### ISSUE TITLE
FYI : We borrowed your code, improved and hosted the game

### ISSUE THREAD

**Issue by foucdeg** [chriz001/Reacteroids#3]
FYI, I released https://asteroids.fouc.net/ which is mainly based on your code.

We removed a few things and added buttons to play on touch screens.
We added a server component so players can see other players' scores. 
It's also a progressive web app (people can add it to their home screen on Android).

The code is here : https://github.com/foucdeg/asteroids
Your licence allows this but I thought I'd let you know.

Best, @foucdeg

**Comment by chriz001** [comment]
@foucdeg Awesome, Thanks for letting me know. I'll be sure to check it out.

Would love to see a link back but that's up to you ;)
